theme: jekyll-theme-minimal
title: [Rise Of The Dead Documentation]
description: [Rise Of The Dead Community runs on a lua sandbox. You can see the full documentation of functions and variables here. If you found a way to break out of the sandbox, please contact me.]